### ISSUE TITLE
A huge mistake has occurred

### ISSUE THREAD

**Issue by Sunsmilktea** [BrassGoggledCoders/SteamAgeRevolution#54]
Forge: 14.23.5.2847
Base:3.13.0
SteamAgeRevolution:1.12.2-0.6.0
A huge error has occurred. I can't get the synthesized item. The recipe will repeat. CastingBlock crashes.

Time: 2019-11-18 22:11:32 CST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at xyz.brassgoggledcoders.steamagerevolution.modules.metalworking.items.ItemHammer.onBlockStartBreak(ItemHammer.java:31)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:302)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

**Comment by Sunsmilktea** [comment]
Alloy forge cannot be used
