### ISSUE TITLE
Crash with dedicated server

### ISSUE THREAD

**Issue by LemADEC** [BrassGoggledCoders/SteamAgeRevolution#55]
As of SteamAgeRevolution-1.12.2-0.6.0, dedicated server crashes with anvil creation due to invalid reference to Gui class on server side.
Consider using the a separate class for Gui and separate client specific methods with the `@SideOnly(Side.CLIENT)` annotation.

```
java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
        at xyz.brassgoggledcoders.steamagerevolution.modules.metalworking.multiblock.hammer.blocks.BlockSteamHammerAnvil.createTileEntity(BlockSteamHammerAnvil.java:29)
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
        at net.minecraft.world.World.redirect$impl$getTileOrNullIfMarkedForRemoval$zll000(World.java:7906)
        at net.minecraft.world.WorldServer.redirect$impl$getTileOrNullIfMarkedForRemoval$zll000(WorldServer.java:4198)
        at net.minecraft.world.World.func_175625_s(World.java:2402)
        at cofh.core.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:184)
        at cofh.core.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:199)
        at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:178)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.onNeighborBlockChange(DuctUnit.java:283)
        at cofh.thermaldynamics.multiblock.MultiBlockFormer.checkMultiBlock(MultiBlockFormer.java:33)
        at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:23)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.formGrid(DuctUnit.java:252)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.singleTick(DuctUnit.java:349)
        at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:84)
        at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1571_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1253)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1203)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 26 more
```

Full mods list: https://www.curseforge.com/minecraft/modpacks/fsg-arcania-craft/files/2831846

**Comment by LemADEC** [comment]
Any update on this?
